[package]
name = "loot"
version = "0.6.0"
authors = ["Miles Egan <miles@plastaq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
globwalk = "0.9.1"
regex = "1.10.6"
unicode-normalization = "0.1.23"
deunicode = "1.6.0"
tempfile = "3.12.0"
rayon = "1.10.0"
lofty = "0.21.0"
filetime = "0.2.25"
