[package]
name = "loot"
version = "0.2.0"
authors = ["Miles Egan <miles@plastaq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
globwalk = "0.9.0"
regex = "1.10.2"
unicode-normalization = "0.1.22"
deunicode = "1.4.2"
tempfile = "3.8.1"
rayon = "1.8.0"
lofty = "0.17.1"
