[package]
name = "loot"
version = "0.3.0"
authors = ["Miles Egan <miles@plastaq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
globwalk = "0.9.1"
regex = "1.10.4"
unicode-normalization = "0.1.23"
deunicode = "1.4.4"
tempfile = "3.10.1"
rayon = "1.10.0"
lofty = "0.19.2"
filetime = "0.2.23"
