[package]
name = "loot"
version = "0.1.0"
authors = ["Miles Egan <miles@plastaq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
globwalk = "0.8.1"
regex = "1.4.6"
unicode-normalization = "0.1.17"
deunicode = "1.3.1"
tempfile = "3.3.0"
rayon = "1.5.3"
lofty = "0.8.1"
